name: "vins_estimator"
version: "0.1.0"
description: "An optimization-based multi-sensor state estimator."
maintainers:
  - name: "fins"
    email: "fins@sjtu.edu.cn"
depends:
  Eigen3: "3.4.0"
  Sophus: "1.22.4"
  Ceres: "1.14.0"
  glog: "0.6.0"
  gflags: "system"
  OpenMP: "system"
  
  nav_msgs: "system"
  sensor_msgs: "system"
  geometry_msgs: "system"

  PCL: "system"
  OpenCV: "3.4.16"

recipes:
  Ceres:
    git: "https://github.com/ceres-solver/ceres-solver.git"
    build_system: "cmake"
    versions:
      "1.14.0":
        tag: "1.14.0"
        cmake_args:
          - "-DSUITESPARSE=OFF"
          - "-DCMAKE_CXX_STANDARD=14"
          - "-DTBB=OFF"
          - "-DMINIGLOG=ON"
          - "-DBUILD_TESTING=OFF"
          - "-DBUILD_EXAMPLES=OFF"
          - "-DCMAKE_CXX_FLAGS=-Wno-error=unused-parameter"
          
licenses:
  - "GPL-3.0"